---
abstract: 'Ensure CSS and JS links in web pages point to real files'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-ValidateHeadLinks
provides:
  MojoX::ValidateHeadLinks:
    file: lib/MojoX/ValidateHeadLinks.pm
    version: 1.03
requires:
  Getopt::Long: 2.38
  Hash::FieldHash: 0.12
  Log::Handler: 0.75
  Mojolicious: 3.3
  Pod::Usage: 1.51
  Try::Tiny: 0.11
  feature: 1.2
  strict: 1.03
  warnings: 1.03
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 1.03
